# client/Dockerfile

# Step 1: 기본 이미지로 Node.js 22 사용
FROM node:22 AS build

# Step 2: 작업 디렉토리 설정
WORKDIR /app

# Step 3: 패키지 파일 복사 및 의존성 설치
COPY package.json yarn.lock ./
RUN yarn install

# Step 4: 코드 복사 및 빌드
COPY . .
RUN yarn build

# Step 5: 실제 배포 이미지 생성
FROM node:22 AS production

WORKDIR /app
COPY --from=build /app ./

# Next.js 애플리케이션 시작
CMD ["yarn", "start"]