# docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Next.js 클라이언트 포트

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Nest.js 서버 포트

  fortune-server:
    build:
      context: ./fortune-server
      dockerfile: Dockerfile
    ports:
      - "5501:5501"  # FastAPI 서버 포트

  payment-server:
    build:
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "5505:5505"  # Echo 서버 포트