# payment-server/Dockerfile

# Step 1: 기본 이미지로 Go 1.23 사용
FROM golang:1.23

# Step 2: 작업 디렉토리 설정
WORKDIR /app

# Step 3: Go 모듈 파일 복사 및 의존성 설치
COPY go.mod go.sum ./
RUN go mod download

# Step 4: 코드 복사 및 빌드
COPY . .
RUN go build -o payment-server ./cmd/main.go

# Step 5: 애플리케이션 실행
CMD ["./payment-server"]