# fortune-server/Dockerfile

# Step 1: 기본 이미지로 Python 3.9 사용
FROM python:3.9

# Step 2: 작업 디렉토리 설정
WORKDIR /app

# Step 3: 필요한 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Step 4: 코드 복사
COPY . .

# Step 5: 애플리케이션 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5501"]