# Build stage
FROM python:3.9 AS build
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# 환경 변수 파일을 제외하고 복사
COPY . .

# Production stage
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --from=build /app .
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5501"]